export const CONTACT_SELECTED_ACTION = {
  SET_CONTACT_SELECTED: "SET_CONTACT_SELECTED",
};
export const CONTACTS_ACTION = {
  ADD_CONTACT: "ADD_CONTACT",
  DELETE_CONTACT: "DELETE_CONTACT",
};
export const USER_CHAT_ACTION = {
  ADD_MESSAGE: "ADD_MESSAGE",
  EDIT_MESSAGE: "EDIT_MESSAGE",
  DELETE_MESSAGE: "DELETE_MESSAGE",
  DELETE_CHAT: "DELETE_CHAT",
};
export const VIEW_MODE_ACTION = {
  TOGGLE_MODE: "TOGGLE_MODE",
};
